# Generated by Django 3.2.4 on 2022-01-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('D', 'Drawing'), ('P', 'Painting')], max_length=50),
        ),
    ]
