# Generated by Django 3.2.4 on 2022-01-18 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_contactus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='fname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='lname',
        ),
    ]
